repository:
  #SQLITE, MYSQL or MONGODB
  type: "SQLITE"
  #If you have selected MYSQL or MONGODB, configure the connection data here
  host: "127.0.0.1:3306"
  database: "your_database"
  username: "your_username"
  password: "your_password"